name: 'action-deploy-config'
description: 'action-deploy-config'
inputs:
  branch:
    description: 'Current branch name'
    required: true
  branch-prod:
    description: 'Production branch name'
    required: true
  branch-dev:
    description: 'Development branch name'
    required: true
  target-stage:
    description: 'Target stage (qa, staging)'
    required: false
outputs:
  deploy_stage:
    description: 'Deploy stage'
  image_tag:
    description: 'Image tag'
  aws_access_key:
    description: 'AWS access key'
  aws_secret_key:
    description: 'AWS secret key'
  aws_account:
    description: 'AWS account'

runs:
  using: 'node16'
  main: 'dist/index.js'
