name: Test this action

on:
  push:
    branches:
      - master
    tags:
      - v**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test this action (dev)
        id: dev
        uses: ./
        with:
          branch: dev
          branch-prod: master
          branch-dev: dev

      - name: Test this action (action)
        id: action
        uses: decompanyio/action-deploy-config@master
        with:
          branch: ${{ github.ref_name }}
          branch-prod: prod
          branch-dev: master

      - name: Check result
        run: |
          echo 'Deploy Stage(prod) : ${{ steps.prod.outputs.deploy_stage }}'
          echo 'Image Tag(prod) : ${{ steps.prod.outputs.image_tag }}'
          echo 'AWS access key(prod) : ${{ steps.prod.outputs.aws_access_key }}'
          echo 'AWS secret key(prod) : ${{ steps.prod.outputs.aws_secret_key }}'
          echo ''
          echo 'Deploy Stage(dev) : ${{ steps.dev.outputs.deploy_stage }}'
          echo 'Image Tag(dev) : ${{ steps.dev.outputs.image_tag }}'
          echo 'AWS access key(dev) : ${{ steps.dev.outputs.aws_access_key }}'
          echo 'AWS secret key(dev) : ${{ steps.dev.outputs.aws_secret_key }}'
          echo ''
          echo 'Deploy Stage(staging) : ${{ steps.staging.outputs.deploy_stage }}'
          echo 'Image Tag(staging) : ${{ steps.staging.outputs.image_tag }}'
          echo 'AWS access key(staging) : ${{ steps.staging.outputs.aws_access_key }}'
          echo 'AWS secret key(staging) : ${{ steps.staging.outputs.aws_secret_key }}'
